"""add is_salon to barbers

Revision ID: 1a31ef5c6fe9
Revises: 3f03840100ae
Create Date: 2026-08-28 01:07:10.384980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a31ef5c6fe9'
down_revision: Union[str, Sequence[str], None] = '3f03840100ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('barbers', sa.Column('is_salon', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('barbers', 'is_salon')
    # ### end Alembic commands ###
